# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiltypleasure', '0002_auto_20160823_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='guiltypleasure.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Billing', to='guiltypleasure.Billing'),
        ),
    ]
