# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guiltypleasure', '0004_productmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_id',
        ),
    ]
