# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiltypleasure', '0005_auto_20160824_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guiltypleasure.Product'),
        ),
    ]
