# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiltypleasure', '0007_auto_20160825_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guiltypleasure.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guiltypleasure.Billing'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
