# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guiltypleasure', '0008_auto_20160826_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ord_Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='ord_prod',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiltypleasure.Order'),
        ),
        migrations.AddField(
            model_name='ord_prod',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiltypleasure.Product'),
        ),
    ]
