# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiltypleasure', '0009_auto_20160826_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord_prod',
            name='price_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ord_prod',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
